# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    default_locale: en
    enabled_locales: ['en', 'pl']
    translator:
        default_path: '%kernel.project_dir%/translations'
        enabled: true
        fallbacks: ['en']
        paths:
            - '%kernel.project_dir%/translations'
    session:
        enabled: true
        handler_id: ~

    secret: '%env(APP_SECRET)%'
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
